apiVersion: v1
kind: ConfigMap
data:
  AWS_BUCKET: kamo-udagram-bucket
  AWS_PROFILE: default
  AWS_REGION: eu-east-2
  JWT_SECRET: testing
  POSTGRES_DB: postgres
  POSTGRES_HOST: udagram-db.cii0cgoo5lpk.us-east-1.rds.amazonaws.com
  URL: localhost:8100
metadata:
  name: env-config